[tool.poetry]
name = "app_python"
version = "0.1.0"
description = "A simple app that shows current time"
authors = ["Alexander a.kurmazov@innopolis.university"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.81"
uvicorn = "^0.18"
pytz = "^2022.2"
types-pytz = "^2022.2.1"
pydantic = "^1.10"
starlette-exporter = "^0.14.0"
fastapi-health = "^0.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0"
isort = "^5.10"
mypy = "^0.971"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
requests = "^2.28.1"
freezegun = "^1.0.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = [
    "tests/*",
    "*site-packages*",
]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 100

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry>=1.2.0"]
build-backend = "poetry.masonry.api"
