apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  labels:
    app: app-python
    chart: '{{ .Chart.Name }}-{{ .Chart.Version}}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
type: Opaque
data:
  key: dmFsdWU=