version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    command: poetry run uvicorn server.app:app --host 0.0.0.0
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000