name: App Python CI
on:
  push:
    paths:
      - app_python/**

env:
  TIMEZONE: 'Europe/Moscow'

jobs:
  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: severity-threshold=high

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./app_python

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install make
          python -m pip install --no-cache-dir poetry==1.2.0
          python -m poetry install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
