name: App Python CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          apt-get update && apt-get -y install make
          python -m pip install --no-cache-dir poetry==1.2.0
          python -m poetry install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
